### PR TITLE
ITSADSSD27953 25788 UQ Maps deliverables

### PR DESCRIPTION
**Pull request by uqmchu**

### CODE REVIEW

**Review by uqtgeor4 — COMMENTED** [review]
4F. With search value AND category item opened
EXAMPLE ISN'T SHOWING

**Comment by uqmchu** [comment]
> 4F. With search value AND category item opened
> EXAMPLE ISN'T SHOWING

Mine's fine?

**Comment by uqtgeor4** [comment]
4F is showing fine now.

**Review by uqtgeor4 — APPROVED** [review]
Looks good

**Review by uqnm — APPROVED** [review]
its a bit weird and not sure about the 'deliverables' category but happy to include now

**Pull request merged**
