### PR TITLE
33883 site nav subnav refactor

### PR DESCRIPTION
**Pull request by jen-lui**

### CODE REVIEW

**Review by Bcrunk — COMMENTED** [review]
The Menu button does not have ARIA tags on first load. only after interaction.

**Review by Bcrunk — CHANGES_REQUESTED** [review]
Works really well, tested with Windows Narrator, still seems to be a few holes in the anouncements, not sure if that is a narrator issue or our usage of aria tags. But I would address those later when we have a more robust accessibility testing. 

Still think on load it needs the aria states?

**Comment by Bcrunk** [comment]
> 
> 
> The Menu button does not have ARIA tags on first load. only after interaction.

Without further insight and more robust testing we will leave this to a future test.

**Review by Bcrunk — APPROVED** [review]

**Comment by jen-lui** [comment]
> > The Menu button does not have ARIA tags on first load. only after interaction.
> 
> Without further insight and more robust testing we will leave this to a future test.

Agreed, my initial thought is there might be too much "noise" for screen readers to announce states when there has been no interaction. The same applies not just to the menu button but all the sub-nav toggle buttons too. Including this as a reference as it also does not have aria tags on load, only after interaction: https://www.w3.org/WAI/tutorials/menus/flyout/#use-button-as-toggle

**Pull request merged**
