### PR TITLE
32754 typography refactor

### PR DESCRIPTION
**Pull request by jen-lui**

### CODE REVIEW

**Comment by Bcrunk** [comment]
The table works well for the summary. 

Couple of question regarding the cleanup 

1. The reference to monospace font usage, was this to confusing or unnessessary? 
2. Is there no value in providing some basic usage guidance, and referring them back to the written style guide. I agree the current format is lacking. 

3. If we are removing the inline elements (If we want these i think they would be better in the Body section or part of Patterns/layouts) would we also remove the Styles section or at least simplify to be more generic... ie. headings are 1.4 line height, rather than focus on Lead text, Paragraph, H1. Or can we combine some of the line items where there is no variation. 

The first pass was kind of to see if this information worked better here or not. 

I think we also cover some of the examples in other areas. like Text utility classes under Body.

**Comment by jen-lui** [comment]
@Bcrunk Replies to your questions:

1. Unnecessary
2. I've added back the link to the written style guide.  I think pulling items out of the guide and listing them as bullet points is extra maintenance.  I do think there is a difference in typography style and writing style and in the revised IA, I had imagined a resources section under "Getting started" would contain links out to brand guidelines, web publishing, written style guide, etc
3. I think including all the inline items is overkill. The typography styles section should showcase styles provided by the DS, not browser default styles. 

I think this branch should just cover the clean up of the Typography section and the review and refactor of the Body component will be separate. Once that happens, the typography section may need to be updated based on outcomes. 

I've kept each heading and element as a separate row in the table for easy reference and to be able to quickly scan and find an element, similar to other DS. I think grouping headings would be problematic as they use different fonts and the line-heights, font-weights may change.

**Review by Bcrunk — COMMENTED** [review]
if we do have a better example structure in the future, we might include in core pages and component pages some kind of list that reference the related examples . 

A lot of those inline styles were not customised. The intention of having them there was so we could also see they were not handled. In the future it might be worth a review to see if we do want to customise any of them and then  add them back into the documentation. 
 
last thing is things like the Paragraph small ... that should be a utility class

**Review by Bcrunk — APPROVED** [review]

**Review by uqnm — APPROVED** [review]
Looks good to me

**Pull request merged**
